[package]
name = "gitai"
version = "0.0.1"
edition = "2021"
authors = ["Jacob Bourne"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
git2 = "0.16.1"
